[package]
name = "llpr"
version = "0.1.0"
authors = ["Ferruccio Barletta <ferruccio.barletta@gmail.com>"]
build = "build.rs"

[dependencies]
quick-error = "1.2.2"
phf = "0.7.23"

[build-dependencies]
phf_codegen = "0.7.23"
